services:
  database:
    image: 'postgres:latest'
    environment:
      USER:
      PASSWORD:
    volumes:
      - db-data:/var/lib/postgresql/data/
  
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
  
volumes: 
  db-data: